#include "video_ext.h"

//#ifndef GL_ARB_multitexture
PFNGLACTIVETEXTUREARBPROC   pglActiveTextureARB = NULL;
PFNGLMULTITEXCOORD2FARBPROC pglMultiTexCoord2fARB = NULL;
//#endif

//#ifndef GL_EXT_framebuffer_object
PFNGLGENFRAMEBUFFERSEXTPROC         pglGenFramebuffersEXT = NULL;
PFNGLBINDFRAMEBUFFEREXTPROC         pglBindFramebufferEXT = NULL;
PFNGLFRAMEBUFFERTEXTURE2DEXTPROC    pglFramebufferTexture2DEXT = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC  pglCheckFramebufferStatusEXT = NULL;
PFNGLDELETEFRAMEBUFFERSEXTPROC      pglDeleteFramebuffersEXT = NULL;
//#endif

//#ifndef GL_ARB_vertex_buffer_object
PFNGLGENBUFFERSARBPROC              pglGenBuffersARB = NULL;
PFNGLBINDBUFFERARBPROC              pglBindBufferARB = NULL;
PFNGLBUFFERDATAARBPROC              pglBufferDataARB = NULL;
PFNGLDELETEBUFFERSARBPROC           pglDeleteBuffersARB = NULL;
PFNGLBUFFERSUBDATAARBPROC           pglBufferSubDataARB = NULL;
//#endif

PFNGLDELETEOBJECTARBPROC        pglDeleteObjectARB = NULL;
PFNGLCREATESHADEROBJECTARBPROC  pglCreateShaderObjectARB = NULL;
PFNGLSHADERSOURCEARBPROC        pglShaderSourceARB = NULL;
PFNGLCOMPILESHADERARBPROC       pglCompileShaderARB = NULL;
PFNGLCREATEPROGRAMOBJECTARBPROC pglCreateProgramObjectARB = NULL;
PFNGLATTACHOBJECTARBPROC        pglAttachObjectARB = NULL;
PFNGLLINKPROGRAMARBPROC         pglLinkProgramARB = NULL;
PFNGLUSEPROGRAMOBJECTARBPROC    pglUseProgramObjectARB = NULL;

PFNGLGETUNIFORMLOCATIONARBPROC   pglGetUniformLocationARB = NULL;
PFNGLUNIFORM1IARBPROC            pglUniform1iARB = NULL;
PFNGLUNIFORM1FARBPROC            pglUniform1fARB = NULL;
PFNGLUNIFORM4FVARBPROC           pglUniform4fvARB = NULL;
PFNGLGETOBJECTPARAMETERIVARBPROC pglGetObjectParameterivARB = NULL;
PFNGLGETINFOLOGARBPROC           pglGetInfoLogARB = NULL;
